apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
images:
  - name: civicpulse-backend
    newName: ghcr.io/tayyabhamad/civicpulse-backend
    newTag: REPLACE_WITH_GIT_SHA
  - name: civicpulse-frontend
    newName: ghcr.io/tayyabhamad/civicpulse-frontend
    newTag: REPLACE_WITH_GIT_SHA
